const express = require('express');
const authController = require('../controllers/authController');
const adminController = require('../controllers/adminController');
const constants = require('../utils/constants');
const router = express.Router();
router.use(authController.protect(true));
router.use(authController.restrictTo(constants.USER_TYPES.ADMIN));
router.post('/skill', adminController.addSkill);
router.post('/language', adminController.addLanguage);
router.post('/jobtitle', adminController.addJobTitle);
router.post('/category', adminController.addCategory);
router.delete('/skill/:id', adminController.deleteSkill);
router.delete('/language/:id', adminController.deleteLanguage);
router.delete('/jobtitle/:id', adminController.deleteJobTitle);
router.delete('/category/:id', adminController.deleteCategory);
router.patch('/skill/:id', adminController.updateSkill);
router.get('/appliedjobscount', adminController.getCountJobs);
module.exports = router;
