const exprience_needed_list = ["No experience", "Less than 1 year", "1 year", "2 years", "3 years","4 years","5 years", "More than 5 years"];
const career_level_list = ["Student", "Entry Level", "Experienced", "Manager", "Senior Management"];
const job_category_list = 
[
    "Accounting/Finance",
    "Administration",
    "Banking",
    "R&D/Science",
    "Engineering - Construction/Civil/Architecture",
    "Business Development",
    "Creative/Design/Art",
    "Customer Service/Support",
    "Writing/Editorial",
    "Hospitality/Hotels/Food Services",
    "Human Resources",
    "Installation/Maintenance/Repair",
    "IT/Software Development",
    "Legal",
    "Logistics/Supply Chain",
    "Operations/Management",
    "Manufacturing/Production",
    "Marketing/PR/Advertising",
    "Medical/Healthcare",
    "Other",
    "Project/Program Management",
    "Quality",
    "Analyst/Research",
    "Sales/Retail",
    "Media/Journalism/Publishing",
    "Sports and Leisure",
    "Fashion",
    "Pharmaceutical",
    "Tourism/Travel",
    "Purchasing/Procurement",
    "Strategy/Consulting",
    "C-Level Executive/GM/Director",
    "Engineering - Telecom/Technology",
    "Engineering - Mechanical/Electrical",
    "Engineering - Oil & Gas/Energy",
    "Engineering - Other",
    "Education/Teaching",
    "Training/Instructor",
  ]

export {exprience_needed_list, career_level_list, job_category_list};